"""initial schema

Revision ID: df7f4495e384
Revises:
Create Date: 2026-09-13 09:59:57.946323
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "df7f4495e384"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "event_type",
            sa.Enum(
                "model_output",
                "human_decision",
                "guardrail_action",
                "threshold_change",
                name="audit_event_type",
            ),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=96), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_digest", sa.String(length=64), nullable=True),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.CheckConstraint("char_length(digest) = 64", name="ck_audit_digest_len"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest"),
    )
    op.create_index(op.f("ix_audit_records_actor"), "audit_records", ["actor"], unique=False)
    op.create_index(
        op.f("ix_audit_records_event_type"), "audit_records", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_occurred_at"), "audit_records", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_request_id"), "audit_records", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_audit_records_sequence"), "audit_records", ["sequence"], unique=True)
    op.create_index(
        op.f("ix_audit_records_subject_id"), "audit_records", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_subject_type"), "audit_records", ["subject_type"], unique=False
    )
    op.create_index(
        "ix_audit_type_time", "audit_records", ["event_type", "occurred_at"], unique=False
    )
    op.create_table(
        "breaker_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "from_state",
            sa.Enum("closed", "open", "half_open", name="breaker_state"),
            nullable=False,
        ),
        sa.Column(
            "to_state", sa.Enum("closed", "open", "half_open", name="breaker_state"), nullable=False
        ),
        sa.Column("trigger", sa.String(length=64), nullable=False),
        sa.Column("observed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("from_state <> to_state", name="ck_breaker_state_changes"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cost_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("spend_date", sa.Date(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("completion_tokens >= 0", name="ck_ledger_completion_nonneg"),
        sa.CheckConstraint("cost_usd >= 0.0", name="ck_ledger_cost_nonneg"),
        sa.CheckConstraint("prompt_tokens >= 0", name="ck_ledger_prompt_nonneg"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(op.f("ix_cost_ledger_session_id"), "cost_ledger", ["session_id"], unique=False)
    op.create_index(op.f("ix_cost_ledger_spend_date"), "cost_ledger", ["spend_date"], unique=False)
    op.create_index(
        "ix_ledger_session_date", "cost_ledger", ["session_id", "spend_date"], unique=False
    )
    op.create_table(
        "guardrail_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "input_filter",
                "injection",
                "schema_validator",
                "grounding",
                "thresholds",
                "budget",
                "circuit_breaker",
                name="guardrail_stage",
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum("passed", "modified", "blocked", name="guardrail_outcome"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guardrail_actions_outcome"), "guardrail_actions", ["outcome"], unique=False
    )
    op.create_index(
        op.f("ix_guardrail_actions_request_id"), "guardrail_actions", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_guardrail_actions_stage"), "guardrail_actions", ["stage"], unique=False
    )
    op.create_index(
        "ix_guardrail_stage_outcome", "guardrail_actions", ["stage", "outcome"], unique=False
    )
    op.create_table(
        "lots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lot_name", sa.String(length=64), nullable=False),
        sa.Column("wafer_count", sa.Integer(), nullable=False),
        sa.Column("split", sa.Enum("train", "val", "holdout", name="split_name"), nullable=False),
        sa.Column("lot_ordinal", sa.Integer(), nullable=False),
        sa.Column("derived_date", sa.Date(), nullable=False),
        sa.Column("derivation_rule", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("lot_ordinal >= 0", name="ck_lots_ordinal_nonneg"),
        sa.CheckConstraint("wafer_count > 0", name="ck_lots_wafer_count_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lots_derived_date"), "lots", ["derived_date"], unique=False)
    op.create_index(op.f("ix_lots_lot_name"), "lots", ["lot_name"], unique=True)
    op.create_index(op.f("ix_lots_split"), "lots", ["split"], unique=False)
    op.create_index("ix_lots_split_ordinal", "lots", ["split", "lot_ordinal"], unique=False)
    op.create_table(
        "model_artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("classifier", "calibrator", "embedder", "faiss_index", name="artifact_kind"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("data_hash", sa.String(length=64), nullable=False),
        sa.Column("git_commit", sa.String(length=40), nullable=False),
        sa.Column("git_dirty", sa.Boolean(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("hyperparameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("label_count", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(content_hash) = 64", name="ck_artifacts_content_hash_len"),
        sa.CheckConstraint("char_length(data_hash) = 64", name="ck_artifacts_data_hash_len"),
        sa.CheckConstraint("label_count >= 0", name="ck_artifacts_label_count_nonneg"),
        sa.ForeignKeyConstraint(["parent_id"], ["model_artifacts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_artifacts_kind_active", "model_artifacts", ["kind", "is_active"], unique=False
    )
    op.create_index(
        op.f("ix_model_artifacts_content_hash"), "model_artifacts", ["content_hash"], unique=True
    )
    op.create_index(
        op.f("ix_model_artifacts_data_hash"), "model_artifacts", ["data_hash"], unique=False
    )
    op.create_index(
        op.f("ix_model_artifacts_is_active"), "model_artifacts", ["is_active"], unique=False
    )
    op.create_table(
        "reason_codes",
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("applies_to", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applies_to_gates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "threshold_changes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("changed_by", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("old_value", sa.Float(), nullable=False),
        sa.Column("new_value", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("old_value <> new_value", name="ck_threshold_actually_changed"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_threshold_changes_name"), "threshold_changes", ["name"], unique=False)
    op.create_table(
        "active_rounds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column(
            "strategy",
            sa.Enum(
                "entropy", "diversity", "entropy_diversity", "random", name="sampling_strategy"
            ),
            nullable=False,
        ),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("diversity_weight", sa.Float(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("labels_before", sa.Integer(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("batch_size > 0", name="ck_round_batch_positive"),
        sa.ForeignKeyConstraint(["artifact_id"], ["model_artifacts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("round_number", "strategy", name="uq_round_number_strategy"),
    )
    op.create_table(
        "drift_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decision_count", sa.Integer(), nullable=False),
        sa.Column("override_rate", sa.Float(), nullable=False),
        sa.Column("expected_calibration_error", sa.Float(), nullable=False),
        sa.Column("input_psi", sa.Float(), nullable=False),
        sa.Column("per_class", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("decision_count >= 0", name="ck_drift_count_nonneg"),
        sa.CheckConstraint(
            "override_rate >= 0.0 AND override_rate <= 1.0", name="ck_drift_override_range"
        ),
        sa.CheckConstraint("window_end > window_start", name="ck_drift_window_ordered"),
        sa.ForeignKeyConstraint(["artifact_id"], ["model_artifacts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drift_snapshots_artifact_id"), "drift_snapshots", ["artifact_id"], unique=False
    )
    op.create_table(
        "historical_excursions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.String(length=96), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column(
            "observed_pattern",
            sa.Enum(
                "center",
                "donut",
                "edge_loc",
                "edge_ring",
                "loc",
                "near_full",
                "random",
                "scratch",
                "none",
                name="defect_pattern",
            ),
            nullable=False,
        ),
        sa.Column("pattern_share", sa.Float(), nullable=False),
        sa.Column(
            "resolved_cause",
            sa.Enum(
                "tool_drift",
                "chamber_condition",
                "recipe_change",
                "material_lot",
                "handling_mechanical",
                "metrology_artifact",
                "upstream_process",
                "unknown",
                name="cause_category",
            ),
            nullable=False,
        ),
        sa.Column("resolution_text", sa.Text(), nullable=False),
        sa.Column("centroid", sa.LargeBinary(), nullable=True),
        sa.Column("is_derived", sa.Boolean(), nullable=False),
        sa.Column("derivation_rule", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pattern_share > 0.0 AND pattern_share <= 1.0", name="ck_excursion_share_range"
        ),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historical_excursions_evidence_id"),
        "historical_excursions",
        ["evidence_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_historical_excursions_lot_id"), "historical_excursions", ["lot_id"], unique=False
    )
    op.create_index(
        op.f("ix_historical_excursions_observed_pattern"),
        "historical_excursions",
        ["observed_pattern"],
        unique=False,
    )
    op.create_table(
        "hypothesis_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("context_hash", sa.String(length=64), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("abstained", sa.Boolean(), nullable=False),
        sa.Column("abstention_reason", sa.Text(), nullable=True),
        sa.Column("injection_suspected", sa.Boolean(), nullable=False),
        sa.Column("context_gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hypotheses_returned", sa.Integer(), nullable=False),
        sa.Column("hypotheses_grounded", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "abstained IS FALSE OR abstention_reason IS NOT NULL",
            name="ck_hypreq_abstention_reason_required",
        ),
        sa.CheckConstraint("cost_usd >= 0.0", name="ck_hypreq_cost_nonneg"),
        sa.CheckConstraint(
            "hypotheses_grounded <= hypotheses_returned", name="ck_hypreq_grounded_le_returned"
        ),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hypothesis_requests_abstained"), "hypothesis_requests", ["abstained"], unique=False
    )
    op.create_index(
        op.f("ix_hypothesis_requests_context_hash"),
        "hypothesis_requests",
        ["context_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hypothesis_requests_lot_id"), "hypothesis_requests", ["lot_id"], unique=False
    )
    op.create_table(
        "process_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.String(length=96), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "tool_drift",
                "chamber_condition",
                "recipe_change",
                "material_lot",
                "handling_mechanical",
                "metrology_artifact",
                "upstream_process",
                "unknown",
                name="cause_category",
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_derived", sa.Boolean(), nullable=False),
        sa.Column("derivation_rule", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("is_derived IS TRUE", name="ck_process_events_always_derived"),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_process_events_event_date"), "process_events", ["event_date"], unique=False
    )
    op.create_index(
        op.f("ix_process_events_evidence_id"), "process_events", ["evidence_id"], unique=True
    )
    op.create_index(op.f("ix_process_events_lot_id"), "process_events", ["lot_id"], unique=False)
    op.create_table(
        "wafers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("wafer_id", sa.String(length=80), nullable=False),
        sa.Column("wafer_index", sa.Integer(), nullable=False),
        sa.Column("die_size", sa.Float(), nullable=False),
        sa.Column("source_row", sa.BigInteger(), nullable=False),
        sa.Column("raw_height", sa.Integer(), nullable=False),
        sa.Column("raw_width", sa.Integer(), nullable=False),
        sa.Column("grid_height", sa.Integer(), nullable=False),
        sa.Column("grid_width", sa.Integer(), nullable=False),
        sa.Column("grid", sa.LargeBinary(), nullable=False),
        sa.Column("die_total", sa.Integer(), nullable=False),
        sa.Column("die_fail", sa.Integer(), nullable=False),
        sa.Column(
            "dataset_label",
            sa.Enum(
                "center",
                "donut",
                "edge_loc",
                "edge_ring",
                "loc",
                "near_full",
                "random",
                "scratch",
                "none",
                name="defect_pattern",
            ),
            nullable=True,
        ),
        sa.Column("dataset_split_label", sa.String(length=16), nullable=True),
        sa.Column("split", sa.Enum("train", "val", "holdout", name="split_name"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "die_fail >= 0 AND die_fail <= die_total", name="ck_wafers_die_fail_range"
        ),
        sa.CheckConstraint("die_total > 0", name="ck_wafers_die_total_positive"),
        sa.CheckConstraint("grid_height > 0 AND grid_width > 0", name="ck_wafers_grid_positive"),
        sa.CheckConstraint(
            "octet_length(grid) = grid_height * grid_width", name="ck_wafers_grid_bytes_match"
        ),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lot_id", "wafer_index", name="uq_wafers_lot_index"),
        sa.UniqueConstraint("source_row"),
    )
    op.create_index(op.f("ix_wafers_dataset_label"), "wafers", ["dataset_label"], unique=False)
    op.create_index(op.f("ix_wafers_lot_id"), "wafers", ["lot_id"], unique=False)
    op.create_index(op.f("ix_wafers_split"), "wafers", ["split"], unique=False)
    op.create_index("ix_wafers_split_label", "wafers", ["split", "dataset_label"], unique=False)
    op.create_index(op.f("ix_wafers_wafer_id"), "wafers", ["wafer_id"], unique=True)
    op.create_table(
        "hypotheses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "cause_category",
            sa.Enum(
                "tool_drift",
                "chamber_condition",
                "recipe_change",
                "material_lot",
                "handling_mechanical",
                "metrology_artifact",
                "upstream_process",
                "unknown",
                name="cause_category",
            ),
            nullable=False,
        ),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("supporting_signal", sa.Text(), nullable=False),
        sa.Column("contradicting_signal", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confirming_query", sa.Text(), nullable=False),
        sa.Column("eliminating_query", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0", name="ck_hypothesis_conf_range"
        ),
        sa.CheckConstraint("rank >= 1", name="ck_hypothesis_rank_positive"),
        sa.ForeignKeyConstraint(["request_id"], ["hypothesis_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", "rank", name="uq_hypothesis_request_rank"),
    )
    op.create_index(
        op.f("ix_hypotheses_cause_category"), "hypotheses", ["cause_category"], unique=False
    )
    op.create_index(op.f("ix_hypotheses_request_id"), "hypotheses", ["request_id"], unique=False)
    op.create_table(
        "predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wafer_id", sa.UUID(), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column(
            "predicted_label",
            sa.Enum(
                "center",
                "donut",
                "edge_loc",
                "edge_ring",
                "loc",
                "near_full",
                "random",
                "scratch",
                "none",
                name="defect_pattern",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("probabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("entropy", sa.Float(), nullable=False),
        sa.Column(
            "routing_band",
            sa.Enum("auto_commit", "uncertainty_band", "below_floor", name="routing_band"),
            nullable=False,
        ),
        sa.Column("auto_commit_threshold", sa.Float(), nullable=False),
        sa.Column("confidence_floor", sa.Float(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column("inference_ms", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("confidence >= 0.0 AND confidence <= 1.0", name="ck_pred_conf_range"),
        sa.CheckConstraint(
            "confidence_floor < auto_commit_threshold", name="ck_pred_bands_ordered"
        ),
        sa.CheckConstraint("entropy >= 0.0", name="ck_pred_entropy_nonneg"),
        sa.ForeignKeyConstraint(["artifact_id"], ["model_artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wafer_id"], ["wafers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wafer_id", "artifact_id", name="uq_pred_wafer_artifact"),
    )
    op.create_index(
        op.f("ix_predictions_artifact_id"), "predictions", ["artifact_id"], unique=False
    )
    op.create_index(op.f("ix_predictions_entropy"), "predictions", ["entropy"], unique=False)
    op.create_index(
        op.f("ix_predictions_routing_band"), "predictions", ["routing_band"], unique=False
    )
    op.create_index(op.f("ix_predictions_wafer_id"), "predictions", ["wafer_id"], unique=False)
    op.create_table(
        "hypothesis_citations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hypothesis_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.String(length=96), nullable=False),
        sa.Column(
            "evidence_kind",
            sa.Enum(
                "classifier_prediction",
                "die_statistics",
                "similar_lot",
                "process_event",
                name="evidence_kind",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hypothesis_id"], ["hypotheses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hypothesis_id", "evidence_id", name="uq_citation_hyp_evidence"),
    )
    op.create_index(
        op.f("ix_hypothesis_citations_evidence_id"),
        "hypothesis_citations",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hypothesis_citations_hypothesis_id"),
        "hypothesis_citations",
        ["hypothesis_id"],
        unique=False,
    )
    op.create_table(
        "review_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wafer_id", sa.UUID(), nullable=False),
        sa.Column("round_id", sa.UUID(), nullable=True),
        sa.Column("prediction_id", sa.UUID(), nullable=True),
        sa.Column(
            "gate", sa.Enum("label", "confirm", "escalation", name="task_gate"), nullable=False
        ),
        sa.Column(
            "state",
            sa.Enum("pending", "assigned", "completed", "expired", name="task_state"),
            nullable=False,
        ),
        sa.Column("priority", sa.Float(), nullable=False),
        sa.Column("show_prediction", sa.Boolean(), nullable=False),
        sa.Column("assigned_to", sa.String(length=128), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["prediction_id"], ["predictions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["round_id"], ["active_rounds.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["wafer_id"], ["wafers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wafer_id", "gate", "round_id", name="uq_task_wafer_gate_round"),
    )
    op.create_index(
        op.f("ix_review_tasks_assigned_to"), "review_tasks", ["assigned_to"], unique=False
    )
    op.create_index(op.f("ix_review_tasks_gate"), "review_tasks", ["gate"], unique=False)
    op.create_index(op.f("ix_review_tasks_round_id"), "review_tasks", ["round_id"], unique=False)
    op.create_index(op.f("ix_review_tasks_state"), "review_tasks", ["state"], unique=False)
    op.create_index(op.f("ix_review_tasks_wafer_id"), "review_tasks", ["wafer_id"], unique=False)
    op.create_index(
        "ix_tasks_queue_order", "review_tasks", ["state", "gate", "priority"], unique=False
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("wafer_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.String(length=128), nullable=False),
        sa.Column(
            "action", sa.Enum("accept", "edit", "reject", name="decision_action"), nullable=False
        ),
        sa.Column(
            "chosen_label",
            sa.Enum(
                "center",
                "donut",
                "edge_loc",
                "edge_ring",
                "loc",
                "near_full",
                "random",
                "scratch",
                "none",
                name="defect_pattern",
            ),
            nullable=True,
        ),
        sa.Column(
            "model_label",
            sa.Enum(
                "center",
                "donut",
                "edge_loc",
                "edge_ring",
                "loc",
                "near_full",
                "random",
                "scratch",
                "none",
                name="defect_pattern",
            ),
            nullable=True,
        ),
        sa.Column("model_confidence", sa.Float(), nullable=True),
        sa.Column("is_override", sa.Boolean(), nullable=False),
        sa.Column("prediction_was_shown", sa.Boolean(), nullable=False),
        sa.Column("reason_code", sa.String(length=48), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", sa.Enum("dataset", "reviewer", name="label_source"), nullable=False),
        sa.Column("decision_ms", sa.Integer(), nullable=False),
        sa.Column("hypothesis_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action = 'accept' OR reason_code IS NOT NULL",
            name="ck_decision_reason_required_on_change",
        ),
        sa.CheckConstraint("decision_ms >= 0", name="ck_decision_ms_nonneg"),
        sa.CheckConstraint(
            "model_confidence IS NULL OR (model_confidence >= 0.0 AND model_confidence <= 1.0)",
            name="ck_decision_conf_range",
        ),
        sa.ForeignKeyConstraint(["hypothesis_id"], ["hypotheses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reason_code"], ["reason_codes.code"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wafer_id"], ["wafers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(op.f("ix_decisions_action"), "decisions", ["action"], unique=False)
    op.create_index(op.f("ix_decisions_chosen_label"), "decisions", ["chosen_label"], unique=False)
    op.create_index(
        op.f("ix_decisions_hypothesis_id"), "decisions", ["hypothesis_id"], unique=False
    )
    op.create_index(op.f("ix_decisions_is_override"), "decisions", ["is_override"], unique=False)
    op.create_index(op.f("ix_decisions_reason_code"), "decisions", ["reason_code"], unique=False)
    op.create_index(op.f("ix_decisions_reviewer_id"), "decisions", ["reviewer_id"], unique=False)
    op.create_index(
        "ix_decisions_reviewer_time", "decisions", ["reviewer_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_decisions_wafer_id"), "decisions", ["wafer_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_decisions_wafer_id"), table_name="decisions")
    op.drop_index("ix_decisions_reviewer_time", table_name="decisions")
    op.drop_index(op.f("ix_decisions_reviewer_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_reason_code"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_is_override"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_hypothesis_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_chosen_label"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_action"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index("ix_tasks_queue_order", table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_wafer_id"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_state"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_round_id"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_gate"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_assigned_to"), table_name="review_tasks")
    op.drop_table("review_tasks")
    op.drop_index(op.f("ix_hypothesis_citations_hypothesis_id"), table_name="hypothesis_citations")
    op.drop_index(op.f("ix_hypothesis_citations_evidence_id"), table_name="hypothesis_citations")
    op.drop_table("hypothesis_citations")
    op.drop_index(op.f("ix_predictions_wafer_id"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_routing_band"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_entropy"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_artifact_id"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_index(op.f("ix_hypotheses_request_id"), table_name="hypotheses")
    op.drop_index(op.f("ix_hypotheses_cause_category"), table_name="hypotheses")
    op.drop_table("hypotheses")
    op.drop_index(op.f("ix_wafers_wafer_id"), table_name="wafers")
    op.drop_index("ix_wafers_split_label", table_name="wafers")
    op.drop_index(op.f("ix_wafers_split"), table_name="wafers")
    op.drop_index(op.f("ix_wafers_lot_id"), table_name="wafers")
    op.drop_index(op.f("ix_wafers_dataset_label"), table_name="wafers")
    op.drop_table("wafers")
    op.drop_index(op.f("ix_process_events_lot_id"), table_name="process_events")
    op.drop_index(op.f("ix_process_events_evidence_id"), table_name="process_events")
    op.drop_index(op.f("ix_process_events_event_date"), table_name="process_events")
    op.drop_table("process_events")
    op.drop_index(op.f("ix_hypothesis_requests_lot_id"), table_name="hypothesis_requests")
    op.drop_index(op.f("ix_hypothesis_requests_context_hash"), table_name="hypothesis_requests")
    op.drop_index(op.f("ix_hypothesis_requests_abstained"), table_name="hypothesis_requests")
    op.drop_table("hypothesis_requests")
    op.drop_index(
        op.f("ix_historical_excursions_observed_pattern"), table_name="historical_excursions"
    )
    op.drop_index(op.f("ix_historical_excursions_lot_id"), table_name="historical_excursions")
    op.drop_index(op.f("ix_historical_excursions_evidence_id"), table_name="historical_excursions")
    op.drop_table("historical_excursions")
    op.drop_index(op.f("ix_drift_snapshots_artifact_id"), table_name="drift_snapshots")
    op.drop_table("drift_snapshots")
    op.drop_table("active_rounds")
    op.drop_index(op.f("ix_threshold_changes_name"), table_name="threshold_changes")
    op.drop_table("threshold_changes")
    op.drop_table("reason_codes")
    op.drop_index(op.f("ix_model_artifacts_is_active"), table_name="model_artifacts")
    op.drop_index(op.f("ix_model_artifacts_data_hash"), table_name="model_artifacts")
    op.drop_index(op.f("ix_model_artifacts_content_hash"), table_name="model_artifacts")
    op.drop_index("ix_artifacts_kind_active", table_name="model_artifacts")
    op.drop_table("model_artifacts")
    op.drop_index("ix_lots_split_ordinal", table_name="lots")
    op.drop_index(op.f("ix_lots_split"), table_name="lots")
    op.drop_index(op.f("ix_lots_lot_name"), table_name="lots")
    op.drop_index(op.f("ix_lots_derived_date"), table_name="lots")
    op.drop_table("lots")
    op.drop_index("ix_guardrail_stage_outcome", table_name="guardrail_actions")
    op.drop_index(op.f("ix_guardrail_actions_stage"), table_name="guardrail_actions")
    op.drop_index(op.f("ix_guardrail_actions_request_id"), table_name="guardrail_actions")
    op.drop_index(op.f("ix_guardrail_actions_outcome"), table_name="guardrail_actions")
    op.drop_table("guardrail_actions")
    op.drop_index("ix_ledger_session_date", table_name="cost_ledger")
    op.drop_index(op.f("ix_cost_ledger_spend_date"), table_name="cost_ledger")
    op.drop_index(op.f("ix_cost_ledger_session_id"), table_name="cost_ledger")
    op.drop_table("cost_ledger")
    op.drop_table("breaker_events")
    op.drop_index("ix_audit_type_time", table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_subject_type"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_subject_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_sequence"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_request_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_occurred_at"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_event_type"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_actor"), table_name="audit_records")
    op.drop_table("audit_records")
    # ### end Alembic commands ###
