"""Assembling the evidence bundle for a lot from the database and the index.

This module decides what the agent is allowed to know, which makes it part of the
guardrail surface even though it lives under retrieval. Two rules govern it.

Only real rows become evidence. Nothing is synthesized to fill a gap: if a lot
has no similar precedent, the bundle simply has no ``hx:`` entries, and the
agent's correct response to a thin bundle is to abstain.

Every returned item carries the ``evidence_id`` the grounding gate will check
against, generated by the same functions the ingest layer used. A description is
returned alongside so the console can render a citation as something a reviewer
can actually read, without the agent ever having authored that text.
"""

from __future__ import annotations

from typing import Any

import numpy as np
from sqlalchemy import select
from sqlalchemy.orm import Session

from yieldloop.agent.context import (
    classifier_evidence,
    die_statistics_evidence,
    process_event_evidence,
    similar_lot_evidence,
)
from yieldloop.agent.schemas import (
    ClassifierEvidence,
    DieStatisticsEvidence,
    ProcessEventEvidence,
    SimilarLotEvidence,
)
from yieldloop.config import Settings
from yieldloop.db.models import HistoricalExcursion, Lot, Prediction, ProcessEvent, Wafer
from yieldloop.ingest.normalize import DieStatistics, decode_grid, die_statistics
from yieldloop.logging import get_logger
from yieldloop.retrieval.index import RetrievalIndexError, load_index
from yieldloop.retrieval.search import search

logger = get_logger(__name__)

#: Wafers per lot contributed to the bundle. A lot is 25 wafers; sending all of
#: them would spend most of the prompt budget restating near-identical maps.
MAX_WAFERS_PER_LOT = 3


def _statistics_for(wafer: Wafer) -> DieStatistics:
    """Recompute die statistics from the stored grid.

    Recomputed rather than read from the wafer row because the radial profile is
    not stored, and recomputing from the normalized grid keeps the numbers the
    agent sees identical to the pixels the console renders.
    """
    return die_statistics(decode_grid(wafer.grid, wafer.grid_height, wafer.grid_width))


def assemble_for_lot(
    session: Session, settings: Settings, lot: Lot
) -> tuple[dict[str, Any], dict[str, dict[str, str]]]:
    """Build the evidence for one lot.

    Returns:
        A mapping of bundle fields to evidence tuples, and a description of every
        evidence id for the console's citation rendering.
    """
    descriptions: dict[str, dict[str, str]] = {}

    wafers = (
        session.execute(
            select(Wafer)
            .where(Wafer.lot_id == lot.id)
            .order_by(Wafer.die_fail.desc())
            .limit(MAX_WAFERS_PER_LOT)
        )
        .scalars()
        .all()
    )

    classifier: list[ClassifierEvidence] = []
    statistics: list[DieStatisticsEvidence] = []
    for wafer in wafers:
        stats = _statistics_for(wafer)
        die_evidence = die_statistics_evidence(wafer, stats)
        statistics.append(die_evidence)
        descriptions[die_evidence.evidence_id] = {
            "evidence_id": die_evidence.evidence_id,
            "kind": "die_statistics",
            "summary": (
                f"Wafer {wafer.wafer_id}: {stats.die_fail} of {stats.die_total} die failed "
                f"({stats.failure_rate:.2%}), edge concentration {stats.edge_concentration:.2f}."
            ),
        }

        prediction = session.execute(
            select(Prediction)
            .where(Prediction.wafer_id == wafer.id)
            .order_by(Prediction.created_at.desc())
            .limit(1)
        ).scalar_one_or_none()
        if prediction is not None:
            prediction_evidence = classifier_evidence(wafer, prediction)
            classifier.append(prediction_evidence)
            descriptions[prediction_evidence.evidence_id] = {
                "evidence_id": prediction_evidence.evidence_id,
                "kind": "classifier_prediction",
                "summary": (
                    f"Wafer {wafer.wafer_id}: classifier predicts "
                    f"'{prediction.predicted_label.value}' at {prediction.confidence:.0%} "
                    "calibrated confidence."
                ),
            }

    events = (
        session.execute(
            select(ProcessEvent)
            .where(ProcessEvent.lot_id == lot.id)
            .order_by(ProcessEvent.evidence_id)
        )
        .scalars()
        .all()
    )
    process_events: list[ProcessEventEvidence] = []
    for event in events:
        event_evidence = process_event_evidence(event, lot.lot_name)
        process_events.append(event_evidence)
        descriptions[event_evidence.evidence_id] = {
            "evidence_id": event_evidence.evidence_id,
            "kind": "process_event",
            "summary": event.summary,
        }

    similar_lots = _retrieve_similar(session, settings, lot, descriptions)

    logger.info(
        "context_assembled",
        lot=lot.lot_name,
        classifier=len(classifier),
        die_statistics=len(statistics),
        similar_lots=len(similar_lots),
        process_events=len(process_events),
    )
    return (
        {
            "classifier": tuple(classifier),
            "die_statistics": tuple(statistics),
            "similar_lots": tuple(similar_lots),
            "process_events": tuple(process_events),
        },
        descriptions,
    )


def _retrieve_similar(
    session: Session, settings: Settings, lot: Lot, descriptions: dict[str, dict[str, str]]
) -> list[SimilarLotEvidence]:
    """Find historical lots with a similar signature.

    Returns an empty list when the index is absent or the lot has no centroid.
    That is a real state -- retrieval has not been built yet, or this lot has no
    embedding -- and it must produce an abstention downstream rather than an
    error or, worse, invented precedent.
    """
    own = session.execute(
        select(HistoricalExcursion).where(HistoricalExcursion.lot_id == lot.id)
    ).scalar_one_or_none()
    if own is None or own.centroid is None:
        return []

    try:
        index, manifest = load_index(settings.faiss_index_path)
    except (FileNotFoundError, RetrievalIndexError) as exc:
        # Not an error: the index may simply not be built yet. Downstream this
        # produces an abstention, which is the honest answer when there is no
        # precedent to cite.
        logger.warning("retrieval_index_unavailable", error=str(exc))
        return []

    query = np.frombuffer(own.centroid, dtype=np.float32)
    hits = search(
        index,
        manifest,
        query,
        top_k=settings.retrieval_top_k,
        exclude=frozenset({own.evidence_id}),
    )

    results: list[SimilarLotEvidence] = []
    for hit in hits:
        excursion = session.execute(
            select(HistoricalExcursion).where(HistoricalExcursion.evidence_id == hit.identifier)
        ).scalar_one_or_none()
        if excursion is None:
            continue
        neighbour_lot = session.get(Lot, excursion.lot_id)
        if neighbour_lot is None:
            continue
        item = similar_lot_evidence(excursion, neighbour_lot.lot_name, hit.similarity)
        results.append(item)
        descriptions[item.evidence_id] = {
            "evidence_id": item.evidence_id,
            "kind": "similar_lot",
            "summary": (
                f"Lot {neighbour_lot.lot_name}: {excursion.pattern_share:.0%} "
                f"'{excursion.observed_pattern.value}', similarity {hit.similarity:.2f}."
            ),
        }
    return results
